// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using update_dotnet_redux_proj.SQLite;

namespace update_dotnet_redux_proj.Migrations
{
    [DbContext(typeof(FactoryContext))]
    [Migration("20190315202428_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854");

            modelBuilder.Entity("update_dotnet_redux_proj.SQLite.Child", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("childName");

                    b.Property<int>("factoryId");

                    b.HasKey("id");

                    b.ToTable("Children");
                });

            modelBuilder.Entity("update_dotnet_redux_proj.SQLite.Factory", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("Factoryid");

                    b.Property<string>("factoryName");

                    b.HasKey("id");

                    b.HasIndex("Factoryid");

                    b.ToTable("Factories");
                });

            modelBuilder.Entity("update_dotnet_redux_proj.SQLite.Factory", b =>
                {
                    b.HasOne("update_dotnet_redux_proj.SQLite.Factory")
                        .WithMany("Factories")
                        .HasForeignKey("Factoryid");
                });
#pragma warning restore 612, 618
        }
    }
}
